dataset:
  input_file: "data/combined_ion.tsv"
  input_layout: "wide"
  analysis_type: "peptidomics"
  convert_numeric_ptms: True

  annotation_file: null
  condition_column: null
  replicate_column: null
  filename_column: null
  exclude_runs:

  index_column: null
  charge_column: "Charge"
  signal_column: "Intensity"
  qvalue_column: null
  pep_column: null

  peptide_seq_column: "Modified Sequence"
  peptide_start_column: "Start"
  uniprot_column: "Protein ID"
  gene_names_column: "Gene"
  protein_descriptions_column: "Protein Description"
  spectral_counts_column: "Spectral Count"
  precursors_exp_column: null
  ibaq_column: null
  fasta_column: null
  protein_weight: null

preprocessing:
  collapse_all_ptms: false
  peptide_rollup_method: "sum"
  protein_rollup_method: null
  directlfq_cores: 8
  directlfq_min_nonan: 1
  filtering:
    qvalue: 0.01
    pep: 0.003
    min_precursors: 1
    min_linear_intensity: 2
    contaminants_files:
      - "data/Contaminants_2022.fasta"
  normalization:
    method:
      - "log2"
      - "median_equalization"
    reference_tag:
    loess_span: 0.9
  imputation:
    method: "lc_conmed"
    lc_conmed_lod_k: 10
    random_state: 42

analysis:
  sign_threshold: 0.05
  clustering_max: 8000
  only_against: null
  only_contrasts: null
  exports:
    export_plot: true
    export_table: false
    table_use_xlsx: true
    path_plot: "data/proteoflux_report_peptido.pdf"
    path_table: "data/proteoflux_table_peptido.xslx"
    path_h5ad: "data/proteoflux_results_peptido.h5ad"
    umap_n_neighbors: 15
    volcano_top_annotated: 20
  title: "Proteoflux Analysis Report"
  intro_text: |
    This report summarizes the proteomic analysis pipeline applied to your dataset.
    We performed filtering to remove low-confidence identifications and contaminants, normalized intensities,
    imputed missing values, and finally ran Differential Expression analysis using limma.
  footer_text: "Proteomics Core Facility - Biozentrum - University of Basel"
