dataset:
  input_file: "data/data_phospho.tsv"
  input_layout: "long"
  analysis_type: "phospho"
  annotation_file: "data/annot_phospho.tsv"
  exclude_runs: null

  inject_runs:
    flowthrough:
      analysis_type: "peptidomics"
      input_file: "data/data_phospho_FT.tsv"
      annotation_file: null
      is_covariate: True

  index_column: null
  signal_column: "FG.MS2RawQuantity"
  qvalue_column: "PG.Qvalue"
  pep_column: "EG.PEP"

  filename_column: "R.FileName"
  spectral_counts_column: "PG.RunEvidenceCount"
  condition_column: "R.Condition"
  replicate_column: "R.Replicate"

  charge_column: "FG.Charge"
  precursors_exp_column: "PG.NrOfPrecursorsIdentified (Experiment-wide)"
  ibaq_column: "PG.IBAQ"
  fasta_column: "PG.FastaHeaders"
  protein_weight: "PG.MolecularWeight"
  protein_descriptions: "PG.ProteinDescriptions"
  gene_names_column: "PG.Genes"

  uniprot_column: "PG.ProteinGroups"
  stripped_seq_column: "PEP.StrippedSequence"
  peptide_seq_column: "EG.ModifiedSequence"
  peptide_start_column: "PEP.PeptidePosition"
  ptm_proteinlocations_column: "EG.ProteinPTMLocations"
  ptm_positions_column: "EG.PTMPositions [Phospho (STY)]"
  ptm_sites_column: "EG.PTMSites [Phospho (STY)]"
  ptm_probabilities_column: "EG.PTMProbabilities [Phospho (STY)]"

preprocessing:
  pivot_signal_method: "sum"
  directlfq_cores: 8
  directlfq_min_nonan: 2
  phospho:
    stochio_correction_level: "protein"
    multisite_collapse_policy: "duplicate"
    localization_mode: "filter_soft"
    localization_threshold: 0.0
    covariate_pivot_method: "sum"
  filtering:
    qvalue: 0.01
    pep: 0.003
    min_precursors: 1
    min_linear_intensity: 2
    contaminants_files:
      - "data/Contaminants_2022.fasta"
  normalization:
    method:
      - "log2"
      - "median_equalization"
    reference_tag: null
    loess_span: 0.9
  imputation:
    method: "lc_conmed"
    lc_conmed_lod_k: 10
    random_state: 42

analysis:
  sign_threshold: 0.05
  annotation_matrix: false
  only_against: null
  exports:
    export_plot: true
    export_table: false
    table_use_xlsx: true
    path_plot: "data/proteoflux_report_phospho.pdf"
    path_table: "data/proteoflux_table_phospho.xslx"
    path_h5ad: "data/proteoflux_results_phospho.h5ad"
    umap_n_neighbors: 15
    volcano_top_annotated: 20
  title: "Proteoflux Analysis Report"
  intro_text: |
    This report summarizes the proteomic analysis pipeline applied to your dataset.
    We performed filtering to remove low-confidence identifications and contaminants, normalized intensities,
    imputed missing values, and finally ran Differential Expression analysis using limma.
  footer_text: "Proteomics Core Facility - Biozentrum - University of Basel"
