dataset:
  input_file: "data_phospho.tsv"
  input_layout: "long"
  analysis_type: "phospho"
  annotation_file: "annot_phospho.tsv"
  exclude_runs: null

  inject_runs:
    flowthrough:
      indexing_type: "peptidomics"
      input_file: "data_phospho_FT.tsv"
      annotation_file: null
      is_covariate: True
      column_overrides:
        qvalue_column: "PG.Qvalue"
        pep_column: "PG.PEP"
        precursors_exp_column: "PG.NrOfPrecursorsIdentified (Experiment-wide)"

  signal_column: "FG.MS2RawQuantity"
  qvalue_column: "FG.Qvalue"
  pep_column: "EG.PEP"
  index_column: null

  filename_column: "R.FileName"
  spectral_counts_column: "PG.RunEvidenceCount"
  condition_column: "R.Condition"
  replicate_column: "R.Replicate"

  charge_column: "FG.Charge"
  precursors_exp_column: null
  fasta_column: "PG.FastaHeaders"
  protein_descriptions: "PG.ProteinDescriptions"
  gene_names_column: "PG.Genes"
  protein_weight: null
  ibaq_column: null

  uniprot_column: "PG.ProteinGroups"
  stripped_seq_column: "PEP.StrippedSequence"
  peptide_seq_column: "EG.ModifiedSequence"
  peptide_start_column: "PEP.PeptidePosition"
  ptm_proteinlocations_column: "EG.ProteinPTMLocations"
  ptm_positions_column: "EG.PTMPositions [Phospho (STY)]"
  ptm_sites_column: "EG.PTMSites [Phospho (STY)]"
  ptm_probabilities_column: "EG.PTMProbabilities [Phospho (STY)]"

preprocessing:
  peptide_rollup_method: "sum"
  directlfq_cores: 8
  directlfq_min_nonan: 2
  phospho:
    multisite_collapse_policy: "explode"
    localization_filter_mode: "soft"
    localization_filter_threshold: 0.95
    covariate_protein_rollup_method: "directlfq"
  filtering:
    qvalue: 0.01
    pep: 0.1
    min_precursors: 1
    min_linear_intensity: 2
    contaminants_files: null
  normalization:
    method:
      - "log2"
      - "median_equalization"
    reference_tag: null
  imputation:
    method: "lc_conmed"
    lc_conmed_lod_k: 10
    lc_conmed_in_min_obs: 1
    random_state: 42

analysis:
  sign_threshold: 0.05
  only_against: null

exports:
  path_h5ad: "proteoflux_results_phospho.h5ad"
  path_table: "proteoflux_results_phospho.xlsx"
  path_pdf_report: "proteoflux_report_phospho.pdf"
  pdf_report:
    volcano_top_annotated: 20
    title: "Proteoflux Analysis Report"
    intro_text: |
      This report summarizes the proteomic analysis pipeline applied to your dataset.
      We performed filtering to remove low-confidence identifications and contaminants, normalized intensities,
      imputed missing values, and finally ran Differential Expression analysis using limma.
    footer_text: "Proteomics Core Facility - Biozentrum - University of Basel"
