dataset:
  input_file: "searle_test.tsv"
  input_layout: "long"
  analysis_type: "proteomics"
  annotation_file: "annotation_searle.tsv"
  exclude_runs:
  index_column: "PG.ProteinGroups"
  signal_column: "FG.MS2RawQuantity"
  qvalue_column: "PG.Qvalue"
  pep_column: "PG.PEP"
  charge_column: "FG.Charge"
  condition_column: "R.Condition"
  replicate_column: "R.Replicate"
  filename_column: "R.FileName"
  spectral_counts_column: "PG.RunEvidenceCount"
  precursors_exp_column: "PG.NrOfPrecursorsIdentified (Experiment-wide)"
  ibaq_column: "PG.IBAQ"
  fasta_column: "PG.FastaHeaders"
  protein_weight_column: "PG.MolecularWeight"
  protein_descriptions_column: "PG.ProteinDescriptions"
  gene_names_column: "PG.Genes"
  peptide_seq_column: "FG.LabeledSequence"

preprocessing:
  protein_rollup_method: "directlfq"
  peptide_rollup_method: "sum"
  directlfq_cores: 8
  directlfq_min_nonan: 1
  filtering:
    qvalue: 0.01
    pep: 0.01
    min_precursors: 1
    min_linear_intensity: 2
    contaminants_files: null
  normalization:
    method:
      - "log2"
      - "median_equalization_by_tag"
    reference_tag:
      - "HUMAN"
  imputation:
    method: "lc_conmed"
    lc_conmed_lod_k: 10
    random_state: 42

analysis:
  only_against: null
  only_contrasts: null

exports:
  path_h5ad: "proteoflux_results.h5ad"
  path_table: "proteoflux_results.xlsx"
  path_pdf_report: "proteoflux_report.pdf"
  pdf_report:
    volcano_top_annotated: 20
    volcano_sign_threshold: 0.01
    volcano_annotate_infinite: false
    title: "Proteoflux Analysis Report"
    intro_text: |
      This report summarizes the proteomic analysis pipeline applied to your dataset.
      We performed filtering to remove low-confidence identifications and contaminants, normalized intensities,
      imputed missing values, and finally ran Differential Expression analysis using limma.
    footer_text: "Proteomics Core Facility - Biozentrum - University of Basel"
